name: Build
on:
  pull_request:
  push:
    branches:
      - main
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up our JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Copy dist file
      run: |
        cp gradle.properties.dist gradle.properties
    - name: Execute Gradle build
      run: gradlew build
    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk 
