name: Release Build
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Copy dist file
      run: |
        cp gradle.properties.dist gradle.properties
    - name: Add verifai licence to gradle.properties
      shell: bash
      env:
          VERIFAI_LICENCE: ${{ secrets.VERIFAI_LICENCE }}
      run: |
        echo "$VERIFAI_LICENCE" >> gradle.properties
    - name: Install gradle wrapper
      run: gradle wrapper
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Build APK
      run: bash ./gradlew assembleRelease

    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}

    - name: Build Changelog
      id: changelog
      uses: ardalanamini/auto-changelog@v3

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: |
          ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
        asset_name: eduIDverifai-${{ github.ref_name }}.apk
        asset_content_type: application/zip
